import { createHash } from "node:crypto";
import { appendFile, mkdir } from "node:fs/promises";
import { dirname } from "node:path";

export const SPEC_VERSION = "0.1" as const;
export type DecisionStatus = "allow" | "block" | "indeterminate" | "error";
export type Context = { decision_id?: string; run_id?: string; correlation_id?: string; parent_id?: string };
export type Event = { spec_version: typeof SPEC_VERSION; id: string; type: string; source: { name: string; version?: string; instance?: string }; subject: { type: string; id: string }; time: string; context?: Context; ordering?: { sequence?: number; partition?: string }; idempotency_key?: string; data: unknown; extensions?: Record<string, unknown> };
export type DecisionRequest = { spec_version: typeof SPEC_VERSION; decision_id?: string; recommendation: string; action: { type: string; subject: { type: string; id: string }; risk_level?: "low"|"medium"|"high"|"critical" }; context?: Context; mode?: "observe"|"advise"|"enforce"; requirements?: Array<{id:string;description:string;critical:boolean;evidence_types?:string[]}>; events?: Event[]; approval?: {approved:boolean;actor?:string;time?:string}; metadata?: Record<string, unknown> };
export type DecisionResult = { spec_version: typeof SPEC_VERSION; decision_id: string; status: DecisionStatus; action_allowed: boolean; reasons: Array<{code:string;message:string;subject_id?:string}>; conditions: string[]; evaluated_at: string; context?: Context; certificate?: Certificate };
export type Certificate = { spec_version: typeof SPEC_VERSION; id:string; decision_id:string; result:unknown; artifact_hashes:string[]; issued_at:string; supersedes?:string; proof:{algorithm:"SHA-256";digest:string} };
export interface Provider { emit(event:Event):Promise<void>; evaluate(request:DecisionRequest):Promise<DecisionResult>; flush():Promise<void>; shutdown():Promise<void> }

const eventTypes = new Set(["decision.started","decision.requested","decision.evaluated","decision.blocked","decision.approved","decision.completed","claim.declared","claim.updated","claim.supported","claim.contradicted","claim.superseded","claim.rejected","evidence.discovered","evidence.attached","evidence.expired","evidence.invalidated","assumption.declared","assumption.resolved","unknown.declared","unknown.resolved","contradiction.detected","contradiction.resolved","verification.requested","verification.approved","verification.started","verification.completed","verification.failed","proof.issued","proof.revoked","proof.superseded"]);
export function validateEvent(value:Event):void { if(value.spec_version!==SPEC_VERSION)throw new Error("unsupported spec_version"); if(!value.id||!eventTypes.has(value.type)||!value.source?.name||!value.subject?.type||!value.subject?.id||!value.time)throw new Error("invalid protocol event"); }
function sorted(value:unknown):unknown { if(Array.isArray(value))return value.map(sorted); if(value&&typeof value==="object")return Object.fromEntries(Object.keys(value).sort().map(key=>[key,sorted((value as Record<string,unknown>)[key])])); return value; }
export function canonicalJSON(value:unknown):string { return JSON.stringify(sorted(value)); }
export function hash(value:unknown):string { return createHash("sha256").update(canonicalJSON(value)).digest("hex"); }

export class RemoteProvider implements Provider { constructor(private endpoint:string){} async emit(event:Event){validateEvent(event);await this.post("/v1/events",event)} async evaluate(request:DecisionRequest){return this.post<DecisionResult>("/v1/decisions:evaluate",request)} async flush(){} async shutdown(){} private async post<T=void>(path:string,value:unknown):Promise<T>{const response=await fetch(this.endpoint.replace(/\/$/,"")+path,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(value)});if(!response.ok)throw new Error(`epistemic server returned ${response.status}: ${await response.text()}`);return response.json() as Promise<T>} }
export class FileProvider implements Provider { constructor(private path:string){} async emit(event:Event){validateEvent(event);await this.write("event",event)} async evaluate(request:DecisionRequest){await this.write("decision_request",request);return {spec_version:SPEC_VERSION,decision_id:request.decision_id??"offline",status:"indeterminate" as const,action_allowed:false,reasons:[{code:"provider_offline",message:"File provider does not evaluate."}],conditions:[],evaluated_at:new Date().toISOString()}} async flush(){} async shutdown(){} private async write(kind:string,value:unknown){await mkdir(dirname(this.path),{recursive:true});await appendFile(this.path,JSON.stringify({kind,value})+"\n",{mode:0o600})} }
export class NoopProvider implements Provider { async emit(_:Event){} async evaluate(request:DecisionRequest){return {spec_version:SPEC_VERSION,decision_id:request.decision_id??"noop",status:"indeterminate" as const,action_allowed:false,reasons:[{code:"provider_disabled",message:"Epistemic evaluation is disabled."}],conditions:[],evaluated_at:new Date().toISOString()}} async flush(){} async shutdown(){} }
